//[example_output
> ./boost_test_container_lex_default
Running 1 test case...
test.cpp:22: error: in "test_collections_vectors_lex": check a < a has failed.
Collections appear to be equal.
test.cpp:23: error: in "test_collections_vectors_lex": check a < b has failed.
Failure at position 2: 3 >= 2.
test.run-fail.cpp:24: error: in "test_collections_vectors_lex": check c < d has failed

*** 3 failures are detected in the test module "boost_test_container_lex_default"
//]
